import('../components/benefits/benefits.js');
import('../components/features/features.js');
import('../components/footer/footer.js');
import('../components/form/form.js');
import('../components/header/header.js');
import('../components/hero/hero.js');
import('../components/partners/partners.js');
import('../components/plans/plans.js');
import('../components/support/support.js');
